/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.misOfertasEscritorio.UI;

import cl.duoc.misOfertasEscritorio.DAO.ProductoDAO;
import cl.duoc.misOfertasEscritorio.DAO.RubroDAO;
import cl.duoc.misOfertasEscritorio.Entities.Producto;
import cl.duoc.misOfertasEscritorio.Entities.Rubro;
import cl.duoc.misOfertasEscritorio.Entities.Usuario;
import com.sun.istack.internal.logging.Logger;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfTemplate;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Graphics2D;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import javax.swing.table.JTableHeader;

/**
 *
 * @author David
 */
public class ProductMenu extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public ProductMenu() {
        initComponents();
        jDateChooserAddProducto.setEnabled(false);
        populateTable();
        populateComboBox();
        setHeaderColor();
    }

    public ProductMenu(Usuario u) {
        initComponents();
        jDateChooserAddProducto.setEnabled(false);
        populateTable();
        populateComboBox();
        setHeaderColor();
        jLabelLogedAs.setText("Logeado como: " + u.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButtonDeleteProducto = new javax.swing.JButton();
        jButtonAddProduct = new javax.swing.JButton();
        jTextFieldSelectedRubro = new javax.swing.JTextField();
        jTextFieldSelectedCod = new javax.swing.JTextField();
        jTextFieldAddNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldSelectedNombre1 = new javax.swing.JTextField();
        jCheckBoxPerecible = new javax.swing.JCheckBox();
        jDateChooserAddProducto = new com.toedter.calendar.JDateChooser();
        jCbxRubro = new javax.swing.JComboBox<>();
        jButtonEditProducto = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jButtonRestore = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonExport = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        menuProductos = new javax.swing.JLabel();
        menuCategoria = new javax.swing.JLabel();
        menuTiendas = new javax.swing.JLabel();
        menuUsuarios = new javax.swing.JLabel();
        exitMenu = new javax.swing.JLabel();
        jLabelBackHome = new javax.swing.JLabel();
        jLabelLogedAs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(36, 47, 65));
        setMinimumSize(new java.awt.Dimension(1170, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mantenedor Productos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CATEGORIA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NOMBRE PRODUCTO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CATEGORIA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 390, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar Producto");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jButtonDeleteProducto.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDeleteProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDeleteProducto.setForeground(new java.awt.Color(36, 47, 65));
        jButtonDeleteProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/deleteButton.png"))); // NOI18N
        jButtonDeleteProducto.setText("ELIMINAR");
        jButtonDeleteProducto.setBorder(null);
        jButtonDeleteProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteProductoMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonDeleteProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 140, 70));

        jButtonAddProduct.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAddProduct.setForeground(new java.awt.Color(36, 47, 65));
        jButtonAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/saveButton.png"))); // NOI18N
        jButtonAddProduct.setText("GUARDAR");
        jButtonAddProduct.setBorder(null);
        jButtonAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddProductMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 150, 70));

        jTextFieldSelectedRubro.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSelectedRubro.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldSelectedRubro.setForeground(new java.awt.Color(36, 47, 65));
        jTextFieldSelectedRubro.setBorder(null);
        jTextFieldSelectedRubro.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextFieldSelectedRubro.setEnabled(false);
        jPanel1.add(jTextFieldSelectedRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 230, 30));

        jTextFieldSelectedCod.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSelectedCod.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldSelectedCod.setForeground(new java.awt.Color(36, 47, 65));
        jTextFieldSelectedCod.setBorder(null);
        jTextFieldSelectedCod.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextFieldSelectedCod.setEnabled(false);
        jPanel1.add(jTextFieldSelectedCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 230, 30));

        jTextFieldAddNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldAddNombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldAddNombre.setForeground(new java.awt.Color(36, 47, 65));
        jTextFieldAddNombre.setBorder(null);
        jTextFieldAddNombre.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextFieldAddNombre.setMaximumSize(new java.awt.Dimension(0, 40));
        jPanel1.add(jTextFieldAddNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 230, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Editar Productos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CODIGO PRODUCTO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NOMBRE PRODUCTO");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("¿PERECIBLE?");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("FECHA VENCIMIENTO");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jTextFieldSelectedNombre1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSelectedNombre1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldSelectedNombre1.setForeground(new java.awt.Color(36, 47, 65));
        jTextFieldSelectedNombre1.setBorder(null);
        jTextFieldSelectedNombre1.setCaretColor(new java.awt.Color(36, 47, 65));
        jPanel1.add(jTextFieldSelectedNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 230, 30));

        jCheckBoxPerecible.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxPerecible.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxPerecible.setForeground(new java.awt.Color(36, 47, 65));
        jCheckBoxPerecible.setText("Si");
        jCheckBoxPerecible.setBorder(null);
        jCheckBoxPerecible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxPerecibleMouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBoxPerecible, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 50, 30));

        jDateChooserAddProducto.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooserAddProducto.setForeground(new java.awt.Color(36, 47, 65));
        jDateChooserAddProducto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(jDateChooserAddProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 230, 30));

        jCbxRubro.setBackground(new java.awt.Color(255, 255, 255));
        jCbxRubro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCbxRubro.setForeground(new java.awt.Color(36, 47, 65));
        jCbxRubro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCbxRubro.setBorder(null);
        jPanel1.add(jCbxRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 230, 40));

        jButtonEditProducto.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEditProducto.setForeground(new java.awt.Color(36, 47, 65));
        jButtonEditProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/updateButton.png"))); // NOI18N
        jButtonEditProducto.setText("ACTUALIZAR");
        jButtonEditProducto.setBorder(null);
        jButtonEditProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditProductoMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonEditProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 150, 70));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(36, 47, 65));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/updateButton.png"))); // NOI18N
        jButton4.setText("ACTUALIZAR");
        jButton4.setBorder(null);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 150, 70));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 390, 10));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 390, 10));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 390, 10));

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 390, 10));

        jSeparator9.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 390, 10));

        jSeparator10.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 390, 10));

        jButtonRestore.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/restoreButton.png"))); // NOI18N
        jButtonRestore.setBorder(null);
        jButtonRestore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRestoreMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonRestore, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 70, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 540, 800));

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProducto.setBackground(new java.awt.Color(255, 255, 255));
        jTableProducto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTableProducto.setForeground(new java.awt.Color(36, 47, 65));
        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Categoria","Fecha Vencimiento", "¿Activo?"
            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTableProducto.setGridColor(new java.awt.Color(255, 255, 255));
    jTableProducto.setIntercellSpacing(new java.awt.Dimension(2, 2));
    jTableProducto.setSelectionBackground(new java.awt.Color(97, 212, 195));
    jTableProducto.setSelectionForeground(new java.awt.Color(36, 47, 65));
    jTableProducto.setShowHorizontalLines(false);
    jTableProducto.setShowVerticalLines(false);
    jTableProducto.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTableProductoMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTableProducto);

    jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 740, 310));

    jPanel2.setBackground(new java.awt.Color(97, 212, 195));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Mis Productos");
    jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

    jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 120));

    jButtonExport.setBackground(new java.awt.Color(255, 255, 255));
    jButtonExport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jButtonExport.setForeground(new java.awt.Color(36, 47, 65));
    jButtonExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/pdfDownload.png"))); // NOI18N
    jButtonExport.setText("Exportar");
    jButtonExport.setBorder(null);
    jButtonExport.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jButtonExportMouseClicked(evt);
        }
    });
    jPanel3.add(jButtonExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 120, 70));

    getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 740, 800));

    jPanel4.setBackground(new java.awt.Color(255, 255, 255));
    jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    menuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/productMenu.png"))); // NOI18N
    menuProductos.setText("Productos");
    menuProductos.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            menuProductosMouseClicked(evt);
        }
    });
    jPanel4.add(menuProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    menuCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/categoryMenu.png"))); // NOI18N
    menuCategoria.setText("Categoria");
    menuCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            menuCategoriaMouseClicked(evt);
        }
    });
    jPanel4.add(menuCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

    menuTiendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/storeMenu.png"))); // NOI18N
    menuTiendas.setText("Tiendas");
    menuTiendas.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            menuTiendasMouseClicked(evt);
        }
    });
    jPanel4.add(menuTiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

    menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/userMenu.png"))); // NOI18N
    menuUsuarios.setText("Usuarios");
    menuUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            menuUsuariosMouseClicked(evt);
        }
    });
    jPanel4.add(menuUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

    exitMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/exitMenu.png"))); // NOI18N
    exitMenu.setText("Salir");
    exitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            exitMenuMouseClicked(evt);
        }
    });
    jPanel4.add(exitMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, -1, -1));

    jLabelBackHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/backMenu.png"))); // NOI18N
    jLabelBackHome.setText("Home");
    jLabelBackHome.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabelBackHomeMouseClicked(evt);
        }
    });
    jPanel4.add(jLabelBackHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, -1, -1));
    jPanel4.add(jLabelLogedAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

    getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 50));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProductosMouseClicked
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        dispose();
        new ProductMenu().setVisible(true);
    }//GEN-LAST:event_menuProductosMouseClicked

    private void exitMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuMouseClicked
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_exitMenuMouseClicked

    private void menuCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCategoriaMouseClicked
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        dispose();
        new CategoryMenu().setVisible(true);
    }//GEN-LAST:event_menuCategoriaMouseClicked

    private void menuTiendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTiendasMouseClicked
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        dispose();
        new StoreMenu().setVisible(true);
    }//GEN-LAST:event_menuTiendasMouseClicked

    private void menuUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsuariosMouseClicked
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        dispose();
        new UserMenu().setVisible(true);
    }//GEN-LAST:event_menuUsuariosMouseClicked

    private void jLabelBackHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackHomeMouseClicked
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jLabelBackHomeMouseClicked

    private void jTableProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductoMouseClicked
        ProductoDAO pDAO = new ProductoDAO();
        Producto p = new Producto();
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());// TODO add your handling code here:
        int column = 0;
        String id = source.getModel().getValueAt(row, column).toString();
        p = pDAO.findById(Long.valueOf(id));
        jTextFieldSelectedCod.setText(String.valueOf(p.getIdProducto()));
        jTextFieldSelectedNombre1.setText(String.valueOf(p.getNombreProducto()));
        jTextFieldSelectedRubro.setText(String.valueOf(p.getRubroId().getNombreRubro()));
    }//GEN-LAST:event_jTableProductoMouseClicked

    private void jButtonAddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddProductMouseClicked
        ProductoDAO pDAO = new ProductoDAO();
        RubroDAO rDAO = new RubroDAO();
        Producto p = new Producto();
        Long cod;
        try {
            if (verificarCampo(jTextFieldAddNombre, 100)) {
                cod = pDAO.getMaxId();
                p.setIdProducto(++cod);
                p.setNombreProducto(jTextFieldAddNombre.getText());
                p.setRubroId(rDAO.findByName(jCbxRubro.getSelectedItem().toString()));
                p.setIsActive("1");
                if (!jCheckBoxPerecible.isSelected()) {
                    p.setEsPerecible(1);
                    p.setFechaVencimiento("N/A");
                } else {
                    p.setEsPerecible(2);
                    Date today = new Date();
                    if (jDateChooserAddProducto.getDate().after(today) || jDateChooserAddProducto.equals(today)) {
                        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                        String strDate = dateFormat.format(jDateChooserAddProducto.getDate());
                        p.setFechaVencimiento(strDate);
                        pDAO.addProducto(p);
                        JOptionPane.showMessageDialog(null, "Producto con ID: " + p.getIdProducto() + " agregado con exito!");
                        clearTable();
                    } else {
                        JOptionPane.showMessageDialog(null, "Está intentando ingresar un producto vencido.");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe ingresar valor en campo nombre. Largo permitido entre 1 y 100");
                jTextFieldAddNombre.requestFocus();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonAddProductMouseClicked

    private void jCheckBoxPerecibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxPerecibleMouseClicked
        if (!jCheckBoxPerecible.isSelected()) {
            jDateChooserAddProducto.setEnabled(false);
            jDateChooserAddProducto.getDateEditor().setEnabled(false);
            jDateChooserAddProducto.getDateEditor().setDate(null);
        } else {
            jDateChooserAddProducto.setEnabled(true);
            jDateChooserAddProducto.getDateEditor().setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxPerecibleMouseClicked

    private void jButtonEditProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditProductoMouseClicked
        ProductoDAO pDAO = new ProductoDAO();
        Producto p = new Producto();
        String oldName = null;
        try {
            p = pDAO.findById(Long.valueOf(jTextFieldSelectedCod.getText()));
            oldName = p.getNombreProducto();
            if (verificarCampo(jTextFieldSelectedNombre1, 100)) {
                p.setNombreProducto(jTextFieldSelectedNombre1.getText());
                pDAO.editProducto(p);
                JOptionPane.showMessageDialog(null, "Producto con ID: " + p.getIdProducto() + " actualizado con exito! Antiguo: " + oldName + ", Nuevo nombre:" + p.getNombreProducto());
                clearTable();

            } else {
                JOptionPane.showMessageDialog(null, "Debe ingresar valor en campo nombre. Largo permitido entre 1 y 100");
                jTextFieldSelectedNombre1.setText(oldName);
                jTextFieldSelectedNombre1.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar algun item de la lista");
        }
    }//GEN-LAST:event_jButtonEditProductoMouseClicked

    private void jButtonDeleteProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteProductoMouseClicked
        ProductoDAO pDAO = new ProductoDAO();
        Producto p = new Producto();
        try {
            if (verificarCampo(jTextFieldSelectedNombre1, 100)) {
                p = pDAO.findById(Long.valueOf(jTextFieldSelectedCod.getText()));
                p.setIsActive("2");
                pDAO.editProducto(p);
                JOptionPane.showMessageDialog(null, "Prducto con código: " + p.getIdProducto() + " dado de baja exitosamente!");
            } else {
                JOptionPane.showMessageDialog(null, "Debe ingresar valor en campo nombre. Largo permitido entre 1 y 100");
                jTextFieldSelectedNombre1.requestFocus();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar algun item de la lista");
        }
        clearTable();
    }//GEN-LAST:event_jButtonDeleteProductoMouseClicked

    private void jButtonRestoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRestoreMouseClicked
        ProductoDAO pDAO = new ProductoDAO();
        Producto p = new Producto();
        try {
            if ((verificarCampo(jTextFieldSelectedNombre1, 100))) {
                p = pDAO.findById(Long.valueOf(jTextFieldSelectedCod.getText()));
                p.setIsActive("1");
                pDAO.editProducto(p);
                JOptionPane.showMessageDialog(null, "Prducto con código: " + p.getIdProducto() + " activo nuevamente!");
            } else {
                JOptionPane.showMessageDialog(null, "Debe ingresar valor en campo nombre. Largo permitido entre 1 y 100");
                jTextFieldSelectedNombre1.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar algun item de la lista");
        }
        clearTable();
    }//GEN-LAST:event_jButtonRestoreMouseClicked

    private void jButtonExportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExportMouseClicked
        try {
            exportPDF(jTableProducto);
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            JOptionPane.showMessageDialog(null, "¡Exportar productos correcto!");
        }
    }//GEN-LAST:event_jButtonExportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitMenu;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAddProduct;
    private javax.swing.JButton jButtonDeleteProducto;
    private javax.swing.JButton jButtonEditProducto;
    private javax.swing.JButton jButtonExport;
    private javax.swing.JButton jButtonRestore;
    private javax.swing.JComboBox<String> jCbxRubro;
    private javax.swing.JCheckBox jCheckBoxPerecible;
    private com.toedter.calendar.JDateChooser jDateChooserAddProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBackHome;
    private javax.swing.JLabel jLabelLogedAs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JTextField jTextFieldAddNombre;
    private javax.swing.JTextField jTextFieldSelectedCod;
    private javax.swing.JTextField jTextFieldSelectedNombre1;
    private javax.swing.JTextField jTextFieldSelectedRubro;
    private javax.swing.JLabel menuCategoria;
    private javax.swing.JLabel menuProductos;
    private javax.swing.JLabel menuTiendas;
    private javax.swing.JLabel menuUsuarios;
    // End of variables declaration//GEN-END:variables
    private void populateTable() {
        ProductoDAO pDAO = new ProductoDAO();
        DefaultTableModel model = (DefaultTableModel) jTableProducto.getModel();
        List<Producto> lista;
        lista = pDAO.listAll();
        Object rowData[] = new Object[5];
        for (Producto prod : lista) {
            rowData[0] = prod.getIdProducto();
            rowData[1] = prod.getNombreProducto();
            rowData[2] = prod.getRubroId().getNombreRubro();
            rowData[3] = prod.getFechaVencimiento();
            rowData[4] = prod.getIsActive();
            model.addRow(rowData);
        }
    }

    private void populateComboBox() {
        RubroDAO rDAO = new RubroDAO();
        List<Rubro> lista = rDAO.listAll();
        jCbxRubro.removeAllItems();
        DefaultComboBoxModel defaultC = new DefaultComboBoxModel();
        for (Rubro r : lista) {
            defaultC.addElement(r.getNombreRubro());
        }
        jCbxRubro.setModel(defaultC);
    }

    private void clearTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTableProducto.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        jTableProducto.setModel(dtm);
        populateTable();
    }

    /**
     *
     * @param {JTexfield} j - JTexfield que debe ser validado
     * @param {Integer} largo - Largo a validar para j
     * @return
     */
    private boolean verificarCampo(JTextField j, int largo) {
        int largoText;
        if (validarVacio(j)) {
            largoText = j.getText().length();
            if (largoText < largo) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }

    }

    /**
     *
     * @param j
     * @return
     */
    private boolean validarVacio(JTextField j) {
        if (j.getText().trim().length() > 0) {
            return true;
        } else {
            return false;
        }
    }

    private void setHeaderColor() {
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(36, 47, 65));
        headerRenderer.setForeground(Color.WHITE);
        headerRenderer.setBorder(BorderFactory.createEmptyBorder());
        for (int i = 0; i < jTableProducto.getModel().getColumnCount(); i++) {
            jTableProducto.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }

    /**
     *
     * @param jtable
     * @throws FileNotFoundException
     * @throws DocumentException
     */
    private void exportPDF(JTable jtable) throws FileNotFoundException, DocumentException {
        Document document = new Document();
        PdfWriter writer;
        //URL destino
        writer = PdfWriter.getInstance(document, new FileOutputStream("reporteProductos.pdf"));
        document.open();
        PdfContentByte cb = writer.getDirectContent();
        PdfTemplate tp = cb.createTemplate(500, 500);
        Graphics2D g2;
        //Imprimir documento
        g2 = tp.createGraphicsShapes(500, 500);
        jtable.print(g2);
        g2.dispose();
        cb.addTemplate(tp, 30, 300);

        // Cerrar documento
        document.close();
    }

}
