/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.misOfertasEscritorio.UI;

import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author David
 */
public class UserMenu extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public UserMenu() {
        initComponents();
        jDateChooserAddProducto.getDateEditor().setEnabled(false);
    }

    public UserMenu(String s) {
        initComponents();
        jLabelLogedAs.setText("Logeado como: " + s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldSelectedRubro = new javax.swing.JTextField();
        jTextFieldSelectedCod = new javax.swing.JTextField();
        jTextFieldAddNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldSelectedNombre1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jDateChooserAddProducto = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        menuProductos = new javax.swing.JLabel();
        menuCategoria = new javax.swing.JLabel();
        menuTiendas = new javax.swing.JLabel();
        menuUsuarios = new javax.swing.JLabel();
        exitMenu = new javax.swing.JLabel();
        jLabelLogedAs = new javax.swing.JLabel();
        jLabelBackHome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(36, 47, 65));
        setMinimumSize(new java.awt.Dimension(1170, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mantenedor Usuarios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CATEGORIA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NOMBRE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RUBRO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(97, 212, 195));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 300, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(97, 212, 195));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 300, 10));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 300, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(36, 47, 65));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/deleteButton.png"))); // NOI18N
        jButton1.setText("ELIMINAR");
        jButton1.setBorder(null);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 140, 70));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(36, 47, 65));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/updateButton.png"))); // NOI18N
        jButton2.setText("ACTUALIZAR");
        jButton2.setBorder(null);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 150, 70));

        jTextFieldSelectedRubro.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSelectedRubro.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldSelectedRubro.setForeground(new java.awt.Color(36, 47, 65));
        jTextFieldSelectedRubro.setBorder(null);
        jTextFieldSelectedRubro.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextFieldSelectedRubro.setEnabled(false);
        jPanel1.add(jTextFieldSelectedRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 230, 30));

        jTextFieldSelectedCod.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSelectedCod.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldSelectedCod.setForeground(new java.awt.Color(36, 47, 65));
        jTextFieldSelectedCod.setBorder(null);
        jTextFieldSelectedCod.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextFieldSelectedCod.setEnabled(false);
        jPanel1.add(jTextFieldSelectedCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 90, 30));

        jTextFieldAddNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldAddNombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldAddNombre.setForeground(new java.awt.Color(36, 47, 65));
        jTextFieldAddNombre.setBorder(null);
        jTextFieldAddNombre.setCaretColor(new java.awt.Color(36, 47, 65));
        jTextFieldAddNombre.setMaximumSize(new java.awt.Dimension(0, 40));
        jPanel1.add(jTextFieldAddNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 230, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Editar Usuarios");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CODIGO PRODUCTO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NOMBRE PRODUCTO");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("¿PERECIBLE?");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("FECHA VENCIMIENTO");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jTextFieldSelectedNombre1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSelectedNombre1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldSelectedNombre1.setForeground(new java.awt.Color(36, 47, 65));
        jTextFieldSelectedNombre1.setBorder(null);
        jTextFieldSelectedNombre1.setCaretColor(new java.awt.Color(36, 47, 65));
        jPanel1.add(jTextFieldSelectedNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 230, 30));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(36, 47, 65));
        jCheckBox1.setText("Si");
        jCheckBox1.setBorder(null);
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 50, 30));

        jDateChooserAddProducto.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooserAddProducto.setForeground(new java.awt.Color(36, 47, 65));
        jDateChooserAddProducto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(jDateChooserAddProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 230, 30));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(36, 47, 65));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(null);
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 540, 800));

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProducto.setBackground(new java.awt.Color(255, 255, 255));
        jTableProducto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTableProducto.setForeground(new java.awt.Color(36, 47, 65));
        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre Producto", "Rubro", "Activo"
            }
        ));
        Color c = new Color(36,47,65);
        jTableProducto.getTableHeader().setBackground(Color.ORANGE);
        jTableProducto.setGridColor(new java.awt.Color(255, 255, 255));
        jTableProducto.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTableProducto.setSelectionBackground(new java.awt.Color(97, 212, 195));
        jTableProducto.setSelectionForeground(new java.awt.Color(36, 47, 65));
        jTableProducto.setShowHorizontalLines(false);
        jTableProducto.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTableProducto);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 740, 240));

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mis Usuarios");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 120));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 740, 800));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/productMenu.png"))); // NOI18N
        menuProductos.setText("Productos");
        menuProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProductosMouseClicked(evt);
            }
        });
        jPanel4.add(menuProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/categoryMenu.png"))); // NOI18N
        menuCategoria.setText("Categoria");
        menuCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCategoriaMouseClicked(evt);
            }
        });
        jPanel4.add(menuCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        menuTiendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/storeMenu.png"))); // NOI18N
        menuTiendas.setText("Tiendas");
        menuTiendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTiendasMouseClicked(evt);
            }
        });
        jPanel4.add(menuTiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/userMenu.png"))); // NOI18N
        menuUsuarios.setText("Usuarios");
        menuUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuUsuariosMouseClicked(evt);
            }
        });
        jPanel4.add(menuUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        exitMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/exitMenu.png"))); // NOI18N
        exitMenu.setText("Salir");
        exitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMenuMouseClicked(evt);
            }
        });
        jPanel4.add(exitMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, -1, -1));

        jLabelLogedAs.setText("Logeado como: ");
        jPanel4.add(jLabelLogedAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        jLabelBackHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/misOfertasEscritorio/Repository/backMenu.png"))); // NOI18N
        jLabelBackHome.setText("Home");
        jLabelBackHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackHomeMouseClicked(evt);
            }
        });
        jPanel4.add(jLabelBackHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProductosMouseClicked
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        dispose();
        new ProductMenu().setVisible(true);
    }//GEN-LAST:event_menuProductosMouseClicked

    private void exitMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuMouseClicked
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_exitMenuMouseClicked

    private void menuCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCategoriaMouseClicked
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        dispose();
        new CategoryMenu().setVisible(true);    }//GEN-LAST:event_menuCategoriaMouseClicked

    private void menuTiendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTiendasMouseClicked
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        dispose();
        new StoreMenu().setVisible(true);    }//GEN-LAST:event_menuTiendasMouseClicked

    private void menuUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsuariosMouseClicked
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        dispose();
        new UserMenu().setVisible(true);    }//GEN-LAST:event_menuUsuariosMouseClicked

    private void jLabelBackHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackHomeMouseClicked
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jLabelBackHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooserAddProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBackHome;
    private javax.swing.JLabel jLabelLogedAs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JTextField jTextFieldAddNombre;
    private javax.swing.JTextField jTextFieldSelectedCod;
    private javax.swing.JTextField jTextFieldSelectedNombre1;
    private javax.swing.JTextField jTextFieldSelectedRubro;
    private javax.swing.JLabel menuCategoria;
    private javax.swing.JLabel menuProductos;
    private javax.swing.JLabel menuTiendas;
    private javax.swing.JLabel menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
